// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmmczeuppbnlyannxeus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtbWN6ZXVwcGJubHlhbm54ZXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDI5ODMsImV4cCI6MjA2NTM3ODk4M30.mfI3HAEU3pXBs2oCWocZjAl6beHS1_HHdDSkNUJhg8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);